openapi: 3.0.0

tags:
  - name: Posts
    description: Everything about Posts
  - name: Photos
    description: Everything about images loaded with Posts
  - name: Likes
    description: Post's likes
  - name: Places
    description: Post's custom place tag
  - name: Search
    description: Search places functionality
  - name: Users
    description: Operations about user

info:
  title: Travelers API
  description: API for social network for travelers
  version: 1.0.0

paths:
  /posts:
    post:
      summary: Create a new post
      tags:
        - Posts
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Post"
      responses:
        "201":
          description: Post created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Post"
        "400":
          description: Bad Request
        "500":
          description: Server error
  /posts/{postId}:
    get:
      summary: Get a post by ID
      tags:
        - Posts
      parameters:
        - name: postId
          in: path
          description: ID of the post to retrieve
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Post"
        "404":
          description: Not found
        "500":
          description: Server error
  /posts/{postId}/like:
    post:
      summary: Like a post
      tags:
        - Posts
      parameters:
        - name: postId
          in: path
          description: ID of the post to like
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Post liked
        "404":
          description: Not found
        "500":
          description: Server error
    delete:
      summary: Dislike a post
      tags:
        - Posts
      parameters:
        - name: postId
          in: path
          description: ID of the post to like
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Post disliked
        "404":
          description: Post Not found
        "500":
          description: Server error
  /posts/{postId}/comments:
    post:
      summary: Comment on a post
      tags:
        - Posts
      parameters:
        - name: postId
          in: path
          description: ID of the post to comment on
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Comment"
      responses:
        "201":
          description: Comment created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Comment"
        "400":
          description: Bad Request
        "404":
          description: Post Not found
        "500":
          description: Server error
  /posts/{postId}/photos:
    post:
      summary: Load new images
      tags:
        - Photos
      parameters:
        - name: postId
          in: path
          description: ID поста
          required: true
          schema:
            type: integer
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                files:
                  type: array
                  description: Image file
                  items:
                    type: string
                    format: binary
      responses:
        "201":
          description: Photos loaded successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Photo"
        "400":
          description: Load error
        "404":
          description: Post Not Found
        "500":
          description: Server error
    get:
      summary: Get all photos for the post
      tags:
        - Photos
      parameters:
        - name: postId
          in: path
          description: Post id
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Photo"
        "404":
          description: Post Not Found
        "500":
          description: Server error
    delete:
      summary: Delete all photos for the post
      tags:
        - Photos
      parameters:
        - name: postId
          in: path
          description: Post id
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: Successful operation
        "404":
          description: Post Not Found
        "500":
          description: Server error
  /likes/{likeId}:
    get:
      summary: Get likes by id
      tags:
        - Likes
      parameters:
        - name: likeId
          in: path
          description: ID of the like
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Successful operation
        "404":
          description: Post Not found
        "500":
          description: Server error
    delete:
      summary: Delete likes by id
      tags:
        - Likes
      parameters:
        - name: likeId
          in: path
          description: ID of the like
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Successful operation
        "404":
          description: Post Not found
        "500":
          description: Server error
  /places:
    post:
      summary: Create a place
      tags:
        - Places
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Place"
      responses:
        "201":
          description: Place created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Place"
        "400":
          description: Bad Request
        "500":
          description: Server error
  /places/{placeId}:
    get:
      summary: Get place by id
      tags:
        - Places
      parameters:
        - name: placeId
          in: path
          description: ID of the place
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Successful operation
    delete:
      summary: Delete place by id
      tags:
        - Places
      parameters:
        - name: placeId
          in: path
          description: ID of the place
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Successful operation
        "404":
          description: Post Not found
        "500":
          description: Server error
  /places/{placeName}:
    get:
      summary: Get place by name
      tags:
        - Places
      parameters:
        - name: placeName
          in: path
          description: ID of the place
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Successful operation
        "400":
          description: Bad Request
        "500":
          description: Server error
  /places/{placeId}/posts:
    get:
      summary: Get posts for a place
      tags:
        - Places
      parameters:
        - name: placeId
          in: path
          description: ID of the place
          required: true
          schema:
            type: string
      responses:
        "200":
          description: List of posts
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Post"
        "404":
          description: Not found
        "500":
          description: Server error
  /search/places:
    get:
      summary: Search popular travel places
      tags:
        - Search
      parameters:
        - name: query
          in: query
          description: Search query
          required: true
          schema:
            type: string
      responses:
        "200":
          description: List of popular places
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Place"
        "500":
          description: Server error
  /users/{userId}/follow:
    post:
      summary: Follow a user
      tags:
        - Users
      parameters:
        - name: userId
          in: path
          description: ID of the user to follow
          required: true
          schema:
            type: string
      responses:
        "200":
          description: User followed
        "404":
          description: User Not found
        "500":
          description: Server error
  /users/{userId}/feed:
    get:
      summary: Get user feed
      tags:
        - Users
      parameters:
        - name: userId
          in: path
          description: ID of the user
          required: true
          schema:
            type: string
      responses:
        "200":
          description: List of posts in reverse chronological order
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Post"
        "404":
          description: User Not found
        "500":
          description: Server error
  /users/feed:
    get:
      summary: Get other users' feed
      tags:
        - Users
      responses:
        "200":
          description: List of posts in reverse chronological order of all following users
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Post"
        "500":
          description: Server error
components:
  schemas:
    Post:
      type: object
      properties:
        id:
          type: string
        title:
          type: string
        description:
          type: string
        place:
          type: string
        created_at:
          type: string
          format: date-time
        comments:
          type: array
          items:
            $ref: "#/components/schemas/Comment"
            createdAt:
              type: string
              format: date-time
    Photo:
      type: object
      properties:
        id:
          type: string
        post_id:
          type: string
        url:
          type: string
    Comment:
      type: object
      properties:
        id:
          type: string
        postId:
          type: string
        content:
          type: string
        createdAt:
          type: string
          format: date-time
    Place:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
    User:
      type: object
      properties:
        id:
          type: string
        username:
          type: string
        followedUsers:
          type: array
          items:
            type: string
